### ISSUE TITLE
Take a look at Yii framework

### ISSUE THREAD

**Issue by louy2** [aidielse/uPost#1]
http://www.yiiframework.com/tutorials/

**Comment by aidielse** [comment]
I'm looking at it right now! Thanks!

**Comment by aidielse** [comment]
I'm not a big fan of Yii, I don't like how hands-off it is. I like having full control of my database creation and structure. Yii seeks to automate the database creation. I also REALLY don't like using a GUI that creates code that you then copy/paste into our website. Yii creates the code to perform queries, and I really don't like it.

**Comment by louy2** [comment]
You can of course hand code all the queries. I want to use Yii simply because I like MVC.
