### ISSUE TITLE
the "uPost!" box scroll over animation is horrible 

### ISSUE THREAD

**Issue by aidielse** [aidielse/uPost#17]
When I scroll and trigger the animation, it causes my browser to misbehave horribly while the animation is happening. Can we remove this animation and replace it with something else?

**Comment by aidielse** [comment]
Side note, the browser I was using was IceWeasel, which is a weird firefox spinoff.

**Comment by mikeogod** [comment]
If you are talking about the animation on the panels, they will br gone
this weekend
