### ISSUE TITLE
Why do we even need a database?

### ISSUE THREAD

**Issue by aidielse** [aidielse/uPost#22]
why do we need to store the long-term access tokens in a database? why don't we just store it in the session? We will save a huge amount of transaction overhead and local space on the server. Actually, why do we even need a database when we can store everything we need client-side using session tokens? We 100% don't even need a database for our app.

**Comment by mikeogod** [comment]
Well, for starter, we need a database just for the sake of the project, and also I don't think we rely on the client-side too much since it is prone to changes in browsers, and what happens when user declines to save cookies sent from us?

**Comment by aidielse** [comment]
But, we really don't need it for the sake of the project. Is there a requirement that our app has to use a database? I'm 100% sure that if our app would work better without a database, then Prof. Plotka will be  fine with it. 

Browsers are prone to change, but php session variables are stores locally on the server, not client side. so I was in error with my initial statement. 

To reiterate: PHP SESSION information, including things like $_SESSION['user'], are stored on our server. Meaning that the data is much less vulnerable to attack, and the user can't decline to save php session data.

Therefore, the data will be safe if we use php sessions and it will only be accessible by the web app. I think that a database just adds extremely unnecessary complications. We can extend the session duration from seven days to 30 days.

**Comment by aidielse** [comment]
PHP handles the session data and stores it in a local file that only PHP scripts can access.

http://www.php.net/manual/en/intro.session.php

**Comment by aidielse** [comment]
Also, a database is ideal for non-volatile data. The session tokens that we use are volatile and change frequently. So managing the data in sessions is the best way to handle the data.

**Comment by mikeogod** [comment]
I see. You have your point. So, the session data persists and will be accessible from any php script? I didn't know about this in php. 

Like, we can do if($_SESSION["users"]["user_id"]["fb_access_token"] !=NULL), then $_SESSION["user"]=user data like access_token, and then once that user posts anything, we can use $_SESSION["user"]["access_token"] ?  

Are you sure that the value of $_SESSION["users"] are the same among different users?

**Comment by mikeogod** [comment]
We can use database to save data from users for later analysis. I think we need to consult Plotka before we rule out database.

**Comment by aidielse** [comment]
Ok, but what analysis would we do? It's not like we are going to develop an API for uPost eventually or anything. What data analysis are we going to do? Any SNS that we're supporting will have an API. And any SNS with an API will have tons and tons of data that we can just get from the API and do analysis on. I see no reason at all to store any data.

**Comment by aidielse** [comment]
session data will be accessible from any php script until session_destroy()
is called (aka a logout function).

PHP keeps track of specific users, $_SESSION['user'] is relative to the
actual user who is browsing our webapp.

**Comment by aidielse** [comment]
So yeah, Essentially PHP constructs its own database and assigns a unique id (as a key for the data table) to each session. This is how $_SESSION['user'] is different for each user.

**Comment by aidielse** [comment]
I contacted Prof. Plotka and he thought that removing the database and handling all information in sessions through PHP is a good idea.
