### ISSUE TITLE
Facebook login suggestions

### ISSUE THREAD

**Issue by louy2** [aidielse/uPost#5]
https://developers.facebook.com/docs/facebook-login/login-flow-for-web
https://developers.facebook.com/docs/reference/php

**Comment by mikeogod** [comment]
Or we can follow this to just get a long-lived login flow

How to obtain a long-lived Facebook accessToken:
- code is received by calling https://www.facebook.com/dialog/oauth?client_id={app-id} &redirect_uri={redirect-uri}
- use code and your app's infos to send a GET request to: https://graph.facebook.com/oauth/access_token?client_id={app-id}&redirect_uri={redirect-uri}&client_secret={app-secret}&code={code-parameter}
- short lived access token is received in response 
- to exchange for a long lived access token, send a GET to: https://graph.facebook.com/oauth/access_token?grant_type=fb_exchange_token&client_id={appid}&client_secret={app_secret}&%20fb_exchange_token={short_lived_token}
- long lived access token is received in response
- store the long lived access token

**Comment by mikeogod** [comment]
App permissions:
all we need for now is the publish_actions permissions
https://developers.facebook.com/docs/facebook-login/permissions

Access Tokens:
https://developers.facebook.com/docs/facebook-login/access-tokens
